### ISSUE TITLE
cool!

### ISSUE THREAD

**Issue by aquynh** [aaaddress1/vtMal#1]
nice to see this, did you already present it at Hitcon? any slides to share?

keep it up, cheers.

**Comment by aaaddress1** [comment]
sure, my slide is on speakerdeck: speakerdeck.com/aaaddress1/malware-sandbox-emulation-in-python <http://speakerdeck.com/aaaddress1/malware-sandbox-emulation-in-python>
I should add link into README document ;)

Regards,
aaaddress1

**Comment by aquynh** [comment]
thanks, linked to your tool from our website now: http://www.unicorn-engine.org/showcase/

cheers!
